In [22]:
!pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in c:\users\mocim\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\mocim\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: xlrd in c:\users\mocim\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\mocim\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\mocim\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [23]:
import pandas as pd

In [24]:
data = pd.read_excel("C:/Users/mocim/OneDrive/Desktop/Lessons/Week 2/Project/raw_data_shark_attacks.xls")

In [25]:
df = data[["Country", "Activity", "Location", "Sex", "Fatal Y/N", "Species ", "Type"]]

In [26]:
df.columns = df.columns.str.strip()

In [27]:
df.shape

(7097, 7)

In [28]:
df.tail()

,Country,Activity,Location,Sex,Fatal Y/N,Species,Type
7092,AUSTRALIA,Diving,Roebuck Bay,M,Y,NaN,Unprovoked
7093,AUSTRALIA,Pearl diving,NaN,M,Y,NaN,Unprovoked
7094,USA,Swimming,Ocracoke Inlet,M,Y,NaN,Unprovoked
7095,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",M,Y,NaN,Unprovoked
7096,CEYLON (SRI LANKA),Swimming,"Below the English fort, Trincomalee",M,Y,NaN,Unprovoked

### MOCI

In [29]:
df.isna().sum()/len(df) *100

Country       0.704523
Activity      8.214739
Location      7.989291
Sex           8.144286
Fatal Y/N     7.904748
Species      44.117233
Type          0.253628
dtype: float64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7097 entries, 0 to 7096
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    7047 non-null   object
 1   Activity   6514 non-null   object
 2   Location   6530 non-null   object
 3   Sex        6519 non-null   object
 4   Fatal Y/N  6536 non-null   object
 5   Species    3966 non-null   object
 6   Type       7079 non-null   object
dtypes: object(7)
memory usage: 388.2+ KB

- Replace null values for Unknown for Activity, Sex and Fatal Y/N as they are around 8%

In [31]:
df[["Activity", "Sex", "Fatal Y/N"]] = df[["Activity", "Sex", "Fatal Y/N"]].fillna("Unknown")

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\3811356152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["Activity", "Sex", "Fatal Y/N"]] = df[["Activity", "Sex", "Fatal Y/N"]].fillna("Unknown")

- Check duplicates

In [32]:
data.duplicated().sum()

np.int64(0)

In [33]:
df.duplicated().sum()

np.int64(325)

In [34]:
df["Sex"].value_counts()

Sex
M          5689
F           812
Unknown     578
M             6
?             2
F             2
N             2
M F           1
 M            1
m             1
lli           1
M x 2         1
.             1
Name: count, dtype: int64

- Check inconsistent values

In [35]:
df ["Sex"] = df ["Sex"].str.strip()

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\3234921729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ["Sex"] = df ["Sex"].str.strip()

In [36]:
df ["Sex"] = df ["Sex"].str.upper()

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\3511102203.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ["Sex"] = df ["Sex"].str.upper()

In [37]:
df ["Sex"] = df ["Sex"].replace (["?", "UNKNOWN", "N", "M F", "LLI", ".", "M X 2"], "Unknown")

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\2089057638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ["Sex"] = df ["Sex"].replace (["?", "UNKNOWN", "N", "M F", "LLI", ".", "M X 2"], "Unknown")

In [38]:
df["Activity"].nunique()

1614

In [39]:
df["Activity"].value_counts().head(30)

Activity
Surfing            1153
Swimming           1018
Unknown             586
Fishing             494
Spearfishing        393
Wading              178
Bathing             164
Diving              151
Snorkeling          135
Standing            113
Scuba diving         84
Body boarding        63
Body surfing         50
Swimming             47
Boogie boarding      42
Kayaking             41
Free diving          33
Treading water       33
Fell overboard       32
Pearl diving         32
Windsurfing          20
Boogie Boarding      18
Walking              17
Fishing              16
Floating             16
Canoeing             16
Shark fishing        15
Surf fishing         14
Surf-skiing          13
Scuba Diving         13
Name: count, dtype: int64

In [40]:
df["Activity"].value_counts().info()

<class 'pandas.core.series.Series'>
Index: 1614 entries, Surfing to Wreck of  large double sailing canoe
Series name: count
Non-Null Count  Dtype
--------------  -----
1614 non-null   int64
dtypes: int64(1)
memory usage: 25.2+ KB

In [41]:
df["Activity"] = df["Activity"].str.strip().str.lower()

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\3029557794.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Activity"] = df["Activity"].str.strip().str.lower()

In [42]:
df["Activity"].isna().sum()

np.int64(0)

In [43]:
df.loc[df["Activity"].str.contains("surf|Boarding|boarding"), "Activity"] = "Surfing related"
df.loc[df["Activity"].str.contains("fishing"), "Activity"] = "Fishing related"
df.loc[df["Activity"].str.contains("swim"), "Activity"] = "Swimming related"
df.loc[df["Activity"].str.contains("diving"), "Activity"] = "Diving related"
df.loc[df["Activity"] == "Boarding related", "Activity"] = "Surfing related"
df.loc[df["Activity"].str.contains ("walking|playing"), "Activity"] = "Non water activities"

df.loc [df["Activity"] == "Non water activities", "Activity"] = "Other"  # Changed my mind, want them 2 in Others 
df.loc [df["Activity"] == "sea disaster", "Activity"] = "Other"

In [44]:
df.loc [ df["Activity"].str.contains ("kayaking|canoeing|rowing|maybe fell overboard|fell overboard"), "Activity" ] = "Boating related"

In [45]:
df.loc[ df["Activity"].isin(["wading", "bathing", "standing", "treading water", "floating"]), "Activity"] = "Swimming related"
df.loc [ df["Activity"].isin( ["snorkeling"]), "Activity" ] = "Diving related"

In [46]:
activity_counts = df["Activity"].value_counts()

rare_activities = activity_counts [activity_counts < 10].index
df.loc[df["Activity"].isin(rare_activities), "Activity"] = "Other"

In [47]:
df["Activity"].value_counts().head(20)

Activity
Swimming related    1766
Surfing related     1652
Fishing related     1272
Other                977
Diving related       702
unknown              586
Boating related      142
Name: count, dtype: int64

In [48]:
df["Fatal Y/N"].isna().sum()

np.int64(0)

In [49]:
df["Fatal Y/N"].value_counts()

Fatal Y/N
N          4950
Y          1494
Unknown     561
UNKNOWN      71
 N            7
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
N             1
y             1
Name: count, dtype: int64

In [50]:
df["Fatal Y/N"] = df["Fatal Y/N"].str.upper().str.strip()

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\3861697453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fatal Y/N"] = df["Fatal Y/N"].str.upper().str.strip()

In [51]:
df["Fatal Y/N"] = df["Fatal Y/N"].replace({"N": "No","Y": "Yes", "UNKNOWN": "Unknown"})

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\2764064334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fatal Y/N"] = df["Fatal Y/N"].replace({"N": "No","Y": "Yes", "UNKNOWN": "Unknown"})

In [52]:
df["Fatal Y/N"].isna().sum()

np.int64(1)

In [53]:
df["Fatal Y/N"] = df["Fatal Y/N"].fillna ("Unknown")

C:\Users\mocim\AppData\Local\Temp\ipykernel_9540\2170484850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fatal Y/N"] = df["Fatal Y/N"].fillna ("Unknown")

In [54]:
df.loc[ df["Fatal Y/N"].str.contains("F|M|NQ|Y X 2"), "Fatal Y/N"] = "Unknown"

In [55]:
df

,Country,Activity,Location,Sex,Fatal Y/N,Species,Type
0,Australia,Fishing related,Michaelmas Island King George Sound,M,Yes,Great White shark 4.5 m,Unprovoked
1,Brazil,Swimming related,Boa Via gem beach,F,No,Tiger shark 3m,Unprovoked
2,Brazil,Swimming related,PierrebBeach,M,No,Bull shark,Unprovoked
3,Australia,Surfing related,Red Cliff beach Yuraygir National Park,M,No,Bull shark,Unprovoked
4,USA,Surfing related,Cromwell's beach Oahu,M,No,2.4m (8ft) shark,Unprovoked
...,...,...,...,...,...,...,...
7092,AUSTRALIA,Diving related,Roebuck Bay,M,Yes,NaN,Unprovoked
7093,AUSTRALIA,Diving related,NaN,M,Yes,NaN,Unprovoked
7094,USA,Swimming related,Ocracoke Inlet,M,Yes,NaN,Unprovoked
7095,PANAMA,unknown,"Panama Bay 8ºN, 79ºW",M,Yes,NaN,Unprovoked
7096,CEYLON (SRI LANKA),Swimming related,"Below the English fort, Trincomalee",M,Yes,NaN,Unprovoked

In [56]:
df.to_csv("shark_clean.csv", index=False)  #copy

### Hypothesis

In [57]:
df.groupby("Activity")["Fatal Y/N"].value_counts()

Activity          Fatal Y/N
Boating related   No             84
                  Yes            49
                  Unknown         9
Diving related    No            485
                  Yes           147
                  Unknown        70
Fishing related   No           1010
                  Yes           181
                  Unknown        81
Other             No            528
                  Yes           343
                  Unknown       106
Surfing related   No           1470
                  Yes           120
                  Unknown        62
Swimming related  No           1071
                  Yes           546
                  Unknown       149
unknown           No            311
                  Unknown       166
                  Yes           109
Name: count, dtype: int64

In [58]:
df_fatal["Fatal Y/N"].value_counts()

NameError: name 'df_fatal' is not defined

In [ ]:
pd.crosstab(df["Activity"], df["Fatal Y/N"])

df_fatal = df[df["Fatal Y/N"] != "Unknown"]  # Exclude Unknown from rows. But here does nothing because the row is "unknown" lowercase.

In [ ]:
df_fatal = fatal_rate.drop ("unknown")  # Remove unknown rows

In [ ]:
fatal_rate.index

In [ ]:
type (df_fatal)

In [ ]:
# Remove unknown rows from activity 
df_fatal2 = df[df["Activity"] != "unknown"]

In [ ]:
df_fatal2["Activity"].value_counts()

In [ ]:
fatal_rate = (pd.crosstab(df_fatal2["Activity"], df_fatal["Fatal Y/N"], normalize="index") * 100).round (2)

fatal_rate

In [ ]:
fatal_rate.plot (kind ="bar")

Among the recorded shark attacks swimming, surfing and fishing related activities are the most frequent in the dataset. 
Boating related act has the highest fatal rate, followed by swimming. 

The highest non fatal rate is related to surfing related, followed by fishing and diving.

- Gender - activity
- gender - fatal

In [ ]:
gender_fatal ["Sex"].value_counts()

In [ ]:
gender_fatal = df [df["Sex"] != "Unknown" ]

In [ ]:
gender_fatal_rate = (pd.crosstab (gender_fatal ["Sex"], df_fatal ["Fatal Y/N"], normalize = "index")*100).round (2)
gender_fatal_rate

In [ ]:
gender_fatal_rate.plot (kind = "bar")

Male and female had the around the same number of shark attacks recorded. 
Fatal rates are slightly higher in males than females, and non fatal rates slightly lower than female.

In [ ]:
df ["Activity"].value_counts()

In [ ]:
sex_activity_rate = (pd.crosstab (df_fatal2["Activity"], gender_fatal ["Sex"], normalize = "index")*100).round (2)
sex_activity_rate

In [ ]:
gender_fatal ["Sex"].value_counts()

In [ ]:
sex_activity_rate.plot (kind = "bar")

# Not meaningful as males registries are significantly higher than females.

### VILDAN

In [ ]:
import pandas as pd 
data = pd.read_excel("C:/Users/mocim/OneDrive/Desktop/Lessons/Week 2/Project/raw_data_shark_attacks.xls")

In [ ]:
df = data[["Country", "Activity", "Location", "Sex", "Fatal Y/N", "Species ", "Type"]].copy()

In [ ]:
df['Country'].value_counts()

In [ ]:
df['Country'] = df['Country'].str.strip().str.upper()

In [ ]:
df['Country'] = df['Country'].replace({
    'RED SEA?': 'UNKNOWN',
    'ASIA?': 'UNKNOWN',
    'CEYLON (SRI LANKA)': 'SRI LANKA'
})

In [ ]:
df['Country'].value_counts()

In [ ]:
df['Country'].isna().sum()

In [ ]:
df['Country'] = df['Country'].fillna("UNKNOWN")

In [ ]:
df['Country'].value_counts().tail(20)

In [ ]:
country_fixes = {
    'OCEAN': 'UNKNOWN',
    'INDIAN OCEAN?': 'UNKNOWN',
    'AFRICA': 'UNKNOWN',
    'COAST OF AFRICA': 'UNKNOWN',
    'TASMAN SEA': 'UNKNOWN',
    'ITALY / CROATIA': 'UNKNOWN',
    'EQUATORIAL GUINEA / CAMEROON': 'UNKNOWN',
    'BETWEEN PORTUGAL & INDIA': 'UNKNOWN',
    'BAHREIN': 'BAHRAIN',
    'ROATAN': 'HONDURAS',
    'BRITISH NEW GUINEA': 'PAPUA NEW GUINEA',
    'SAN DOMINGO': 'DOMINICAN REPUBLIC'
}

df['Country'] = df['Country'].replace(country_fixes)

LOCATION

In [ ]:
df['Location'].value_counts()

In [ ]:
df['Location'] = df['Location'].str.strip().str.upper()

In [ ]:
df['Location'] = df['Location'].fillna('UNKNOWN')

In [ ]:
df['Location'].value_counts()

In [ ]:
df['Type'].value_counts()

In [ ]:
df['Type'] = df['Type'].str.strip().str.upper()

In [ ]:
df['Type'] = df['Type'].fillna('UNKNOWN')

In [ ]:
df['Type'].value_counts()

In [ ]:
type_fixes = {
    'BOAT': 'WATERCRAFT',
    '?': 'UNKNOWN',
    'UNCONFIRMED': 'UNKNOWN',
    'UNVERIFIED': 'UNKNOWN',
    'UNDER INVESTIGATION': 'UNKNOWN',
    'QUESTIONABLE': 'UNKNOWN',
    'INVALID': 'UNKNOWN'
}

df['Type'] = df['Type'].replace(type_fixes)
df['Type'].value_counts()

In [59]:
df

,Country,Activity,Location,Sex,Fatal Y/N,Species,Type
0,Australia,Fishing related,Michaelmas Island King George Sound,M,Yes,Great White shark 4.5 m,Unprovoked
1,Brazil,Swimming related,Boa Via gem beach,F,No,Tiger shark 3m,Unprovoked
2,Brazil,Swimming related,PierrebBeach,M,No,Bull shark,Unprovoked
3,Australia,Surfing related,Red Cliff beach Yuraygir National Park,M,No,Bull shark,Unprovoked
4,USA,Surfing related,Cromwell's beach Oahu,M,No,2.4m (8ft) shark,Unprovoked
...,...,...,...,...,...,...,...
7092,AUSTRALIA,Diving related,Roebuck Bay,M,Yes,NaN,Unprovoked
7093,AUSTRALIA,Diving related,NaN,M,Yes,NaN,Unprovoked
7094,USA,Swimming related,Ocracoke Inlet,M,Yes,NaN,Unprovoked
7095,PANAMA,unknown,"Panama Bay 8ºN, 79ºW",M,Yes,NaN,Unprovoked
7096,CEYLON (SRI LANKA),Swimming related,"Below the English fort, Trincomalee",M,Yes,NaN,Unprovoked

In [60]:
df.nunique()

Country       253
Activity        7
Location     4639
Sex             3
Fatal Y/N       3
Species      1754
Type           14
dtype: int64

### KEAGAN