In [1]:
import pandas as pd

In [2]:
!pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: openpyxl in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: xlrd in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (2.0.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /Users/vildanpirpiroglu/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
data = pd.read_excel("raw_data_shark_attacks.xls")

In [4]:
data.head(3)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,6th June,2026.0,Unprovoked,Australia,Western Australia,Michaelmas Island King George Sound,Spearfishing,Daniel Turpin,M,35,...,Great White shark 4.5 m,Simon De Marchi: ABC News: 9 News: The Guardian:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1st June,2026.0,Unprovoked,Brazil,Recife,Boa Via gem beach,Swimming,Marcela Vitoria de Lima Santos,F,19,...,Tiger shark 3m,Keith Cowley: Andrew Currie: Kevin McMurray Tr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1st June,2026.0,Unprovoked,Brazil,Jaboatao dos Guarapes,PierrebBeach,Swimming,Joao Lucas Castro Nemezio,M,11,...,Bull shark,Keith Cowley: Andrew Currie: Todd Smith: The U...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.shape # 2.366 rows/person

(7097, 23)

In [6]:
df = data[["Country", "Activity", "Location", "Sex", "Fatal Y/N", "Species ", "Type"]].copy()

In [7]:
df.head()

,Country,Activity,Location,Sex,Fatal Y/N,Species,Type
0,Australia,Spearfishing,Michaelmas Island King George Sound,M,Y,Great White shark 4.5 m,Unprovoked
1,Brazil,Swimming,Boa Via gem beach,F,N,Tiger shark 3m,Unprovoked
2,Brazil,Swimming,PierrebBeach,M,N,Bull shark,Unprovoked
3,Australia,Surfing,Red Cliff beach Yuraygir National Park,M,N,Bull shark,Unprovoked
4,USA,Paddling surfboard,Cromwell's beach Oahu,M,N,2.4m (8ft) shark,Unprovoked

In [8]:
df.columns = df.columns.str.strip()

In [9]:
df.columns

Index(['Country', 'Activity', 'Location', 'Sex', 'Fatal Y/N', 'Species',
       'Type'],
      dtype='str')

In [10]:
df['Country'].value_counts()

Country
USA                   2583
AUSTRALIA             1482
SOUTH AFRICA           597
NEW ZEALAND            144
BAHAMAS                136
                      ...
BAHREIN                  1
KOREA                    1
RED SEA?                 1
ASIA?                    1
CEYLON (SRI LANKA)       1
Name: count, Length: 253, dtype: int64

In [11]:
df['Country'] = df['Country'].str.strip().str.upper()

In [12]:
df['Country'] = df['Country'].replace({
    'RED SEA?': 'UNKNOWN',
    'ASIA?': 'UNKNOWN',
    'CEYLON (SRI LANKA)': 'SRI LANKA'
})

In [13]:
df['Country'].value_counts()

Country
USA                         2583
AUSTRALIA                   1533
SOUTH AFRICA                 599
NEW ZEALAND                  146
BAHAMAS                      142
                            ...
ROATAN                         1
BETWEEN PORTUGAL & INDIA       1
DJIBOUTI                       1
BAHREIN                        1
KOREA                          1
Name: count, Length: 211, dtype: int64

In [14]:
df['Country'].isna().sum()

np.int64(50)

In [15]:
df['Country'] = df['Country'].fillna("UNKNOWN")

In [16]:
df['Country'].value_counts().tail(30)

Country
SLOVENIA                        1
CURACAO                         1
ITALY / CROATIA                 1
MONACO                          1
SAN DOMINGO                     1
KUWAIT                          1
FALKLAND ISLANDS                1
CYPRUS                          1
PARAGUAY                        1
BRITISH NEW GUINEA              1
OCEAN                           1
GEORGIA                         1
SYRIA                           1
TUVALU                          1
INDIAN OCEAN?                   1
ANDAMAN ISLANDS                 1
EQUATORIAL GUINEA / CAMEROON    1
COOK ISLANDS                    1
AFRICA                          1
ALGERIA                         1
COAST OF AFRICA                 1
TASMAN SEA                      1
GHANA                           1
GREENLAND                       1
SWEDEN                          1
ROATAN                          1
BETWEEN PORTUGAL & INDIA        1
DJIBOUTI                        1
BAHREIN                         1
KOREA                           1
Name: count, dtype: int64

In [17]:
country_fixes = {
    'OCEAN': 'UNKNOWN',
    'INDIAN OCEAN?': 'UNKNOWN',
    'AFRICA': 'UNKNOWN',
    'COAST OF AFRICA': 'UNKNOWN',
    'TASMAN SEA': 'UNKNOWN',
    'ITALY / CROATIA': 'UNKNOWN',
    'EQUATORIAL GUINEA / CAMEROON': 'UNKNOWN',
    'BETWEEN PORTUGAL & INDIA': 'UNKNOWN',
    'BAHREIN': 'BAHRAIN',
    'ROATAN': 'HONDURAS',
    'BRITISH NEW GUINEA': 'PAPUA NEW GUINEA',
    'SAN DOMINGO': 'DOMINICAN REPUBLIC'
}

df['Country'] = df['Country'].replace(country_fixes)

LOCATION

In [18]:
df['Location'].value_counts()

Location
New Smyrna Beach, Volusia County       191
Daytona Beach, Volusia County           31
Ponce Inlet, Volusia County             28
Myrtle Beach, Horry County              22
Melbourne Beach, Brevard County         20
                                      ...
                                         1
Roebuck Bay                              1
Ocracoke Inlet                           1
Panama Bay 8ºN, 79ºW                     1
Below the English fort, Trincomalee      1
Name: count, Length: 4639, dtype: int64

In [19]:
df['Location'] = df['Location'].str.strip().str.upper()

In [20]:
df['Location'] = df['Location'].fillna('UNKNOWN')

In [21]:
df['Location'].value_counts()

Location
UNKNOWN                                567
NEW SMYRNA BEACH, VOLUSIA COUNTY       193
DAYTONA BEACH, VOLUSIA COUNTY           34
PONCE INLET, VOLUSIA COUNTY             28
MYRTLE BEACH, HORRY COUNTY              22
                                      ...
                                         1
ROEBUCK BAY                              1
OCRACOKE INLET                           1
PANAMA BAY 8ºN, 79ºW                     1
BELOW THE ENGLISH FORT, TRINCOMALEE      1
Name: count, Length: 4588, dtype: int64

In [22]:
df['Type'].value_counts()

Type
Unprovoked             5245
Provoked                643
Invalid                 552
Watercraft              355
Sea Disaster            242
Questionable             27
Boat                      7
 Provoked                 2
UNprovoked                1
unprovoked                1
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

In [23]:
df['Type'] = df['Type'].str.strip().str.upper()

In [24]:
df['Type'] = df['Type'].fillna('UNKNOWN')

In [25]:
df['Type'].value_counts()

Type
UNPROVOKED             5247
PROVOKED                645
INVALID                 552
WATERCRAFT              355
SEA DISASTER            242
QUESTIONABLE             27
UNKNOWN                  18
BOAT                      7
?                         1
UNCONFIRMED               1
UNVERIFIED                1
UNDER INVESTIGATION       1
Name: count, dtype: int64

In [26]:
type_fixes = {
    'BOAT': 'WATERCRAFT',
    '?': 'UNKNOWN',
    'UNCONFIRMED': 'UNKNOWN',
    'UNVERIFIED': 'UNKNOWN',
    'UNDER INVESTIGATION': 'UNKNOWN',
    'QUESTIONABLE': 'UNKNOWN',
    'INVALID': 'UNKNOWN'
}

df['Type'] = df['Type'].replace(type_fixes)
df['Type'].value_counts()

Type
UNPROVOKED      5247
PROVOKED         645
UNKNOWN          601
WATERCRAFT       362
SEA DISASTER     242
Name: count, dtype: int64