In [1]:
!pip install pandas openpyxl xlrd

Requirement already satisfied: pandas in c:\users\mocim\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\mocim\anaconda3\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mocim\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\mocim\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\mocim\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [3]:
import pandas as pd

In [7]:
data = pd.read_excel("C:/Users/mocim/OneDrive/Desktop/Lessons/Week 2/Project/raw_data_shark_attacks.xls")

In [10]:
data.head(3)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,6th June,2026.0,Unprovoked,Australia,Western Australia,Michaelmas Island King George Sound,Spearfishing,Daniel Turpin,M,35,...,Great White shark 4.5 m,Simon De Marchi: ABC News: 9 News: The Guardian:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1st June,2026.0,Unprovoked,Brazil,Recife,Boa Via gem beach,Swimming,Marcela Vitoria de Lima Santos,F,19,...,Tiger shark 3m,Keith Cowley: Andrew Currie: Kevin McMurray Tr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1st June,2026.0,Unprovoked,Brazil,Jaboatao dos Guarapes,PierrebBeach,Swimming,Joao Lucas Castro Nemezio,M,11,...,Bull shark,Keith Cowley: Andrew Currie: Todd Smith: The U...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.shape # 2.366 rows/person

(7097, 23)

In [25]:
df = data[["Country", "Activity", "Location", "Sex", "Fatal Y/N", "Species ", "Type"]]

In [31]:
df.head()

,Country,Activity,Location,Sex,Fatal Y/N,Species,Type
0,Australia,Spearfishing,Michaelmas Island King George Sound,M,Y,Great White shark 4.5 m,Unprovoked
1,Brazil,Swimming,Boa Via gem beach,F,N,Tiger shark 3m,Unprovoked
2,Brazil,Swimming,PierrebBeach,M,N,Bull shark,Unprovoked
3,Australia,Surfing,Red Cliff beach Yuraygir National Park,M,N,Bull shark,Unprovoked
4,USA,Paddling surfboard,Cromwell's beach Oahu,M,N,2.4m (8ft) shark,Unprovoked

In [27]:
df.columns = df.columns.str.strip()

In [29]:
df.columns

Index(['Country', 'Activity', 'Location', 'Sex', 'Fatal Y/N', 'Species',
       'Type'],
      dtype='object')